import { readdirSync, readFileSync, statSync } from 'node:fs';
import { relative, resolve, sep } from 'node:path';

const EXTENSIONS = new Set(['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs']);

/** Directory names never descended into. */
const IGNORED_DIRS = new Set([
  'node_modules',
  'dist',
  'build',
  'coverage',
  '.git',
  'out',
  '.next',
  '.nuxt',
  '.svelte-kit',
  'vendor',
  'compiled',
]);

/** File-name suffixes excluded by default (tests, generated, declarations). */
const IGNORED_SUFFIXES = [
  '.d.ts',
  '.min.js',
  '.spec.ts',
  '.spec.tsx',
  '.spec.js',
  '.spec.jsx',
  '.test.ts',
  '.test.tsx',
  '.test.js',
  '.test.jsx',
  '.stories.ts',
  '.stories.tsx',
];

/**
 * Sentinel files whose presence marks a whole directory subtree as
 * machine-generated (openapi-generator, swagger-codegen). These generators don't
 * add a per-file @generated banner, so directory-level detection is needed.
 */
const GENERATOR_SENTINELS = new Set([
  '.openapi-generator-ignore',
  '.openapi-generator',
  '.swagger-codegen-ignore',
  '.swagger-codegen',
]);

/** First-line markers that flag machine-generated files. */
const GENERATED_MARKERS = [
  '@generated',
  'this file is generated',
  'do not edit',
  'auto-generated',
  'code generated by',
];

function hasIgnoredSuffix(name: string): boolean {
  const lower = name.toLowerCase();
  return IGNORED_SUFFIXES.some((s) => lower.endsWith(s));
}

const TEST_DIR_NAMES = new Set([
  '__tests__',
  '__mocks__',
  '__snapshots__',
  '__fixtures__',
  'test',
  'tests',
  'fixtures',
  'e2e',
  'benchmarks',
  'benches',
]);

function isInTestDir(relPath: string): boolean {
  const parts = relPath.split('/');
  return parts.some((p) => TEST_DIR_NAMES.has(p));
}

// The same naming conventions read from the other side. Discovery uses them to
// drop files from analysis; orphan detection uses them to tell who keeps a
// symbol alive. Both must agree on what counts as a test, so the rules live
// together — an export held up by a test is a different story from one held up
// by application code, and neither may be guessed at.

function stemOf(relPath: string): string {
  const name = relPath.slice(relPath.lastIndexOf('/') + 1).toLowerCase();
  const dot = name.lastIndexOf('.');
  return dot > 0 ? name.slice(0, dot) : name;
}

/** `foo.test.ts`, `foo.spec.tsx`, or anything under a test directory. */
export function isTestPath(relPath: string): boolean {
  const stem = stemOf(relPath);
  return stem.endsWith('.test') || stem.endsWith('.spec') || isInTestDir(relPath);
}

/** A Storybook story: `Button.stories.tsx`. */
export function isStoryPath(relPath: string): boolean {
  return stemOf(relPath).endsWith('.stories');
}

/** Convert a gitignore-ish glob into a RegExp matched against POSIX rel paths. */
export function globToRegExp(glob: string): RegExp {
  let re = '';
  for (let i = 0; i < glob.length; i++) {
    const ch = glob[i]!;
    if (ch === '*') {
      if (glob[i + 1] === '*') {
        // ** → any number of path segments
        re += '.*';
        i++;
        if (glob[i + 1] === '/') i++; // consume the slash after **
      } else {
        re += '[^/]*';
      }
    } else if (ch === '?') {
      re += '[^/]';
    } else if ('.+^${}()|[]\\'.includes(ch)) {
      re += '\\' + ch;
    } else {
      re += ch;
    }
  }
  return new RegExp(`^${re}$`);
}

/** Any single line this long marks a minified/bundled file. */
const MAX_LINE_LENGTH = 2000;

function looksGeneratedOrBundled(absPath: string): boolean {
  try {
    const head = readFileSync(absPath, 'utf8').slice(0, 64_000);
    if (GENERATED_MARKERS.some((m) => head.slice(0, 500).toLowerCase().includes(m))) return true;
    // bundled/minified: at least one very long line
    let lineLen = 0;
    for (let i = 0; i < head.length; i++) {
      if (head.charCodeAt(i) === 10) lineLen = 0;
      else if (++lineLen > MAX_LINE_LENGTH) return true;
    }
    return false;
  } catch {
    return false;
  }
}

export interface DiscoverOptions {
  ignore: string[];
  /** Skip the generated-marker file read (faster; used in tests). */
  skipGeneratedCheck?: boolean;
}

/** Recursively find analyzable source files under `root`. */
export function discover(root: string, options: DiscoverOptions): string[] {
  const absRoot = resolve(root);
  const userIgnore = options.ignore.map(globToRegExp);
  const found: string[] = [];

  const stat = statSync(absRoot);
  if (stat.isFile()) return [absRoot];

  const walkDir = (dir: string): void => {
    let entries: import('node:fs').Dirent[];
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    // A generator sentinel marks this whole subtree as generated — skip it.
    if (entries.some((e) => GENERATOR_SENTINELS.has(e.name))) return;
    for (const entry of entries) {
      const abs = dir + sep + entry.name;
      const rel = relative(absRoot, abs).split(sep).join('/');
      if (userIgnore.some((re) => re.test(rel))) continue;
      if (entry.isDirectory()) {
        if (IGNORED_DIRS.has(entry.name) || entry.name.startsWith('.')) continue;
        walkDir(abs);
      } else if (entry.isFile()) {
        const dot = entry.name.lastIndexOf('.');
        const ext = dot >= 0 ? entry.name.slice(dot) : '';
        if (!EXTENSIONS.has(ext)) continue;
        if (hasIgnoredSuffix(entry.name)) continue;
        if (isInTestDir(rel)) continue;
        if (!options.skipGeneratedCheck && looksGeneratedOrBundled(abs)) continue;
        found.push(abs);
      }
    }
  };
  walkDir(absRoot);
  return found.sort();
}
